connector:
    name: oro_importexport
    jobs:
        mage_store_import:
            title: "Store import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.store
                        processor: marello_magento.importexport.processor.store
                        writer:    marello_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_store_rest_import:
            title: "Store import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.rest.store
                        processor: marello_magento.importexport.processor.rest.store
                        writer:    marello_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_website_import:
            title: "Website import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.website
                        processor: marello_magento.importexport.processor.website
                        writer:    marello_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_website_rest_import:
            title: "Website import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.rest.website
                        processor: marello_magento.importexport.processor.rest.website
                        writer:    marello_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_product_import:
            title: "Product import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.product_connector
                        processor: marello_magento.importexport.processor.product
                        writer:    marello_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_product_export:
            title: "Product export to Magento"
            type:  export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.importexport.reader.product_export
                        processor: marello_magento.importexport.processor.product_export
                        writer:    marello_magento.importexport.writer.product
                    parameters:
                        batch_size: 1

#        orocommerce_product_import:
#            title: "Sync products from OroCommerce"
#            type: import
#            steps:
#                import:
#                    title: import
#                    class: Oro\Bundle\BatchBundle\Step\ItemStep
#                    services:
#                        reader:    marello_orocommerce.integration.connector.product
#                        processor: oro_importexport.processor.import_delegate
#                        writer:    oro_integration.writer.persistent_batch_writer
#                    parameters:
#                        batch_size: 100
#
#        orocommerce_product_export:
#            title: "Sync products to OroCommerce"
#            type:  export
#            steps:
#                create:
#                    title: export
#                    class: Oro\Bundle\BatchBundle\Step\ItemStep
#                    services:
#                        reader:    marello_orocommerce.importexport.reader.export.product.create
#                        processor: oro_importexport.processor.export_delegate
#                        writer:    marello_orocommerce.importexport.writer.export.product.create
#                    parameters:
#                        batch_size: 100
