parameters:
    marello_magento.orm.repository.class: Doctrine\Common\Persistence\ObjectRepository

services:
    marello_magento.orm.regions_repository:
        class:           %marello_magento.orm.repository.class%
        factory_service: doctrine
        factory_method:  getRepository
        arguments:
            - OroMagentoBundle:Region
