version: '2'
services:
    data:
        image: djocker/orodata

    db:
        image: percona:5.7
        expose:
            - "3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=marellocommerce
            - MYSQL_USER=marellocommerce
            - MYSQL_PASSWORD=marellocommerce
        volumes_from:
            - data

    mailhog:
        image: mailhog/mailhog
        ports:
          - "5083:8025"
        logging:
            driver: "none"

    web:
        build:
            context: environment/.docker
            args:
              - SYMFONY_ENV=test
              - APP_ROOT=/var/www
        working_dir: /var/www/
        links:
            - "db"
            - "mailhog"
        ports:
            - "5080:80"
            - "5081:8080"
        volumes_from:
            - data
        volumes:
            - ./applications/marello-application:/var/www
            - ./package/marello:/package/marello
        environment:
            - APP_ROOT=/var/www
            - VIRTUAL_HOST=marello.docker
            - COMPOSERFILE=dev.json
            - TIMEOUT=3000
            - IS_LOCAL=true
            - CMD_INIT_BEFORE=
            - CMD_INIT_CLEAN=
            - CMD_INIT_INSTALLED=
            - CMD_INIT_AFTER=
            - APP_DB_DRIVER=pdo_mysql
            - APP_DB_HOST=db
            - APP_DB_PORT=3306
            - APP_DB_USER=marellocommerce
            - APP_DB_PASSWORD=marellocommerce
            - APP_DB_NAME=marellocommerce
            - APP_HOSTNAME=marello.docker
            - APP_MAILER_TRANSPORT=smtp
            - APP_MAILER_HOST=mailhog
            - APP_MAILER_PORT=1025
            - APP_MAILER_ENCRYPTION=
            - APP_MAILER_USER=user
            - APP_MAILER_PASSWORD=password
            - APP_WEBSOCKET_HOST=
            - APP_WEBSOCKET_BIND_PORT=5081
            - APP_WEBSOCKET_BACKEND_PORT=5081
            - APP_WEBSOCKET_FRONTEND_PORT=5081
            - APP_IS_INSTALLED=