datagrids:
    marello-enterprise-inventory-warehouse-grid:
        source:
            type: orm
            acl_resource: marello_inventory_warehouse_view
            query:
                select:
                    - w.id
                    - w
                from:
                    - { table: MarelloInventoryBundle:Warehouse, alias: w }
        columns:
            label:
                label: marello.inventory.warehouse.label.label
            default:
                label: marello.inventory.warehouse.default.label
                frontend_type: boolean
        sorters:
            columns:
                label:            { data_name: w.label }
                default:          { data_name: w.default }
            default:
                label: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        filters:
            columns:
                label:
                    type:             string
                    data_name:        w.label
                default:
                    type:             boolean
                    data_name:        w.default
        properties:
            id: ~
            update_link:
                type:   url
                route:  marelloenterprise_inventory_warehouse_update
                params:
                    id: id
            delete_link:
                type:   url
                route:  marelloenterprise_inventory_api_delete_warehouse
                params:
                    id: id
        actions:
            delete:
                type: delete
                link: delete_link
                icon: trash
                confirmation: true
            update:
                type: navigate
                link: update_link
                icon: edit
                rowAction: true
        action_configuration: [@marelloenterprise_inventory.datagrid.action_permission_provider, "getActionPermissions"]
        options:
            mass_actions:
                delete:
                    enabled: false