datagrids:
    marello-enterprise-inventory-warehouse-grid:
        source:
            type: orm
            acl_resource: marelloenterprise_inventory_warehouse_view
            query:
                select:
                    - w.id
                    - w
                    - wt.label as warehouseType
                from:
                    - { table: MarelloInventoryBundle:Warehouse, alias: w }
                join:
                    left:
                        - { join: w.warehouseType, alias: wt }
        columns:
            label:
                label:              marello.inventory.warehouse.label.label
            code:
                label:              marello.inventory.warehouse.code.label
            warehouseType:
                label:              marello.inventory.warehouse.warehousetype.entity_label
                frontend_type:      string
            default:
                label:              marello.inventory.warehouse.default.label
                frontend_type:      boolean
        sorters:
            columns:
                label:              { data_name: w.label }
                code:               { data_name: w.code }
                warehouseType:      { data_name: wt.label }
                default:            { data_name: w.default }
            default:
                label: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC'
        filters:
            columns:
                label:
                    type:             string
                    data_name:        w.label
                code:
                    type:             string
                    data_name:        w.code
                warehouseType:
                    type: entity
                    data_name: wt
                    options:
                        field_options:
                            class: Marello\Bundle\InventoryBundle\Entity\WarehouseType
                default:
                    type:             boolean
                    data_name:        w.default
        properties:
            id: ~
            update_link:
                type:   url
                route:  marelloenterprise_inventory_warehouse_update
                params:
                    id: id
            delete_link:
                type:   url
                route:  marelloenterprise_inventory_api_delete_warehouse
                params:
                    id: id
        actions:
            update:
                type: navigate
                link: update_link
                icon: edit
                rowAction: true
            delete:
                type: delete
                link: delete_link
                icon: trash
                confirmation: true
        action_configuration: ['@marelloenterprise_inventory.datagrid.action_permission_provider', "getActionPermissions"]
        options:
            mass_actions:
                delete:
                    enabled: false