datagrids:
    marelloenterprise-inventory-warehouses-grid:
        source:
            type: orm
            acl_resource: marelloenterprise_inventory_warehouse_view
            query:
                select:
                    - w.id
                    - w
                    - wt.label as warehouseType
                from:
                    - { table: MarelloInventoryBundle:Warehouse, alias: w }
                join:
                    left:
                        - { join: w.warehouseType, alias: wt }
        columns:
            label:
                label:              marello.inventory.warehouse.label.label
            code:
                label:              marello.inventory.warehouse.code.label
            warehouseType:
                label:              marello.inventory.warehousetype.entity_label
                frontend_type:      string
            default:
                label:              marello.inventory.warehouse.default.label
                frontend_type:      boolean
        sorters:
            columns:
                label:              { data_name: w.label }
                code:               { data_name: w.code }
                warehouseType:      { data_name: wt.label }
                default:            { data_name: w.default }
            default:
                label: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC'
        filters:
            columns:
                label:
                    type:             string
                    data_name:        w.label
                code:
                    type:             string
                    data_name:        w.code
                warehouseType:
                    type: entity
                    data_name: wt
                    options:
                        field_options:
                            class: Marello\Bundle\InventoryBundle\Entity\WarehouseType
                default:
                    type:             boolean
                    data_name:        w.default
        properties:
            id: ~
            view_link:
                type:   url
                route:  marelloenterprise_inventory_warehouse_view
                params: [ id ]
            update_link:
                type:   url
                route:  marelloenterprise_inventory_warehouse_update
                params: [ id ]
            delete_link:
                type:   url
                route:  marelloenterprise_inventory_api_delete_warehouse
                params: [ id ]
        actions:
            view:
                type: navigate
                link: view_link
                icon: eye
                rowAction: true
            update:
                type: navigate
                link: update_link
                icon: edit
                rowAction: true
            delete:
                type: delete
                label: oro.grid.action.delete
                link: delete_link
                icon: trash
                rowAction: true
                confirmation: true
        action_configuration: ['@marelloenterprise_inventory.datagrid.action_permission_provider', "getActionPermissions"]
        options:
            mass_actions:
                delete:
                    enabled: false

    marelloenterprise-inventory-warehousegroups-grid:
        source:
            type: orm
            query:
                select:
                    - whg
                from:
                    - { table: MarelloInventoryBundle:WarehouseGroup, alias: whg }
                join:
                    left:
                        - { join: whg.warehouses, alias: wh }
                where:
                    and:
                        - whg.system != true
        columns:
            id:
                label:                marello.inventory.warehousegroup.id.label
                frontend_type:        string
            name:
                label:                marello.inventory.warehousegroup.name.label
                frontend_type:        string
            description:
                label:                marello.inventory.warehousegroup.description.label
                frontend_type:        string
            warehouses:
                label:                marello.inventory.warehousegroup.warehouses.label
                type:                 twig
                frontend_type:        html
                template:             MarelloEnterpriseInventoryBundle:WarehouseGroup/Datagrid:warehouses.html.twig
        filters:
            columns:
                name:
                    type: string
                    data_name: whg.name
        sorters:
            columns:
                id:
                    data_name: whg.id
                name:
                    data_name: whg.name
                description:
                    data_name: whg.description
        properties:
            view_link:
                type:   url
                route:  marelloenterprise_inventory_warehousegroup_view
                params: [ id ]
            update_link:
                type:   url
                route:  marelloenterprise_inventory_warehousegroup_update
                params: [ id ]
            delete_link:
                type:   url
                route:  marelloenterprise_inventory_api_delete_warehousegroup
                params: [ id ]
        actions:
            view:
                type:           navigate
                label:          oro.grid.action.view
                link:           view_link
                icon:           eye
                acl_resource:   marelloenterprise_inventory_warehouse_view
                rowAction:      true
            update:
                type:           navigate
                label:          oro.grid.action.update
                link:           update_link
                icon:           edit
                rowAction:      true
            delete:
                type:           delete
                label:          oro.grid.action.delete
                link:           delete_link
                icon:           trash
                rowAction:      true
                confirmation:   true
        options:
            entity_pagination: true

    marelloenterprise-inventory-not-linked-warehousegroups-grid:
        extends: marelloenterprise-inventory-warehousegroups-grid
        source:
            query:
                join:
                    left:
                        - { join: whg.warehouseChannelGroupLink, alias: wcgl }
                where:
                    and:
                        - wcgl.id IS NULL OR wcgl.id = :linkOwner
            bind_parameters:
                -
                    name: linkOwner
                    default: null
                    type: integer
        filters: ~
        actions: ~

    marelloenterprise-inventory-group-warehouses-grid:
        extends: marelloenterprise-inventory-warehouses-grid
        source:
            query:
                join:
                    left:
                        - { join: w.group, alias: whg }
                where:
                    and:
                        - whg.id = :id
            bind_parameters:
                - id
        filters: ~
        actions: ~

    marelloenterprise-inventory-warehousechannelgrouplinks-grid:
        source:
            type: orm
            query:
                select:
                    - wcgl
                from:
                    - { table: MarelloInventoryBundle:WarehouseChannelGroupLink, alias: wcgl }
                join:
                    left:
                        - { join: wcgl.warehouseGroup, alias: whg }
                        - { join: wcgl.salesChannelGroups, alias: scg }
                where:
                    and:
                        - wcgl.system != true
        columns:
            id:
                label:                marello.inventory.warehousechannelgrouplink.id.label
                frontend_type:        string
            warehouseGroup:
                label:                marello.inventory.warehousechannelgrouplink.warehouse_group.label
                frontend_type:        string
            salesChannelGroups:
                label:                marello.inventory.warehousechannelgrouplink.sales_channel_groups.label
                type:                 twig
                frontend_type:        html
                template:             MarelloEnterpriseInventoryBundle:WarehouseChannelGroupLink/Datagrid:salesChannelGroups.html.twig
        properties:
            update_link:
                type:   url
                route:  marelloenterprise_inventory_warehousechannelgrouplink_update
                params: [ id ]
            delete_link:
                type:   url
                route:  marelloenterprise_inventory_api_delete_warehousechannelgrouplink
                params: [ id ]
        actions:
            update:
                type:           navigate
                label:          oro.grid.action.update
                link:           update_link
                icon:           edit
                acl_resource:   marelloenterprise_inventory_warehousechannelgrouplink_update
                rowAction:      true
            delete:
                type:           delete
                label:          oro.grid.action.delete
                link:           delete_link
                icon:           trash
                rowAction:      true
                confirmation:   true
        options:
            entity_pagination: true

    marelloenterprise-not-linked-warehouse-groups-grid:
        source:
            type: orm
            query:
                select:
                    - scg.id
                    - scg.name
                    - scg.description
                    - >
                        (CASE WHEN (:linkOwner IS NOT NULL) THEN
                            CASE WHEN (scg.id IN (:channelGroups) OR scg.id IN (:data_in)) AND scg.id NOT IN (:data_not_in)
                            THEN true ELSE false END
                        ELSE
                            CASE WHEN scg.id IN (:data_in) AND scg.id NOT IN (:data_not_in)
                            THEN true ELSE false END
                        END) as hasLink
                from:
                    - { table: MarelloInventoryBundle:WarehouseChannelGroupLink, alias: wcgl }
                join:
                    left:
                        - { join: wcgl.salesChannelGroups, alias: scg }
                where:
                    and:
                        - wcgl.system = true OR wcgl.id = :linkOwner
                        - scg.system != true
            bind_parameters:
                -
                    name: linkOwner
                    default: null
                    type: integer
                - channelGroups
        columns:
            hasLink:
                label:                ~
                editable:             true
                frontend_type:        boolean
            id:
                label:                marello.sales.saleschannelgroup.id.label
                frontend_type:        string
            name:
                label:                marello.sales.saleschannelgroup.name.label
                frontend_type:        string
            description:
                label:                marello.sales.saleschannelgroup.description.label
                frontend_type:        string
        sorters:
            columns:
                id:
                    data_name: scg.id
                name:
                    data_name: scg.name
                description:
                    data_name: scg.description
                hasLink:
                    data_name: hasLink
            default:
                hasLink: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC'
        properties:
            id: ~
        options:
            rowSelection:
                dataField: id
                columnName: hasLink
                selectors:
                    included: '#addSalesChannelGroups'
                    excluded: '#removeSalesChannelGroups'
