marelloenterprise_inventory_warehouse_api:
    resource:     "@MarelloEnterpriseInventoryBundle/Controller/Api/Rest/WarehouseController.php"
    type:         rest

marelloenterprise_inventory_wfarule_api:
    resource:     "@MarelloEnterpriseInventoryBundle/Controller/Api/Rest/WFARuleController.php"
    type:         rest
