datagrids:
    marello-invoices-base-grid:
        source:
            type: orm
            query:
                select:
                    - i
                    - sc.name as salesChannelName
                    - o.orderNumber as orderNumber
                from:
                    - { table: MarelloInvoiceBundle:Invoice, alias: i }
                join:
                    left:
                        - { join: i.salesChannel, alias: sc }
                        - { join: i.billingAddress, alias: ba }
                        - { join: i.shippingAddress, alias: sa }
                        - { join: i.order, alias: o }
                        - { join: i.type, alias: it }
        columns:
            invoiceNumber:
                label:            marello.invoice.invoice_number.label
                frontend_type:    string
            orderNumber:
                label:            marello.order.order_number.label
            salesChannel:
                label:            marello.invoice.sales_channel.label
                frontend_type:    string
                data_name:        salesChannelName
            shippingMethod:
                label:            marello.invoice.shipping_method.label
                type:             twig
                frontend_type:    html
                template:         MarelloInvoiceBundle:Invoice/Datagrid/Property:shippingMethod.html.twig
            billingAddress:
                frontend_type:    string
                data_name:        billingName # This alias is generated using InvoiceGridAddressFilterListener
                label:            marello.invoice.billing_address.name.label
            shippingAddress:
                frontend_type:    string
                data_name:        shippingName # This alias is generated using InvoiceGridAddressFilterListener
                label:            marello.invoice.shipping_address.name.label
            grandTotal:
                label:            marello.invoice.grand_total.label
                type:             localized_number
                method:           formatCurrency
                context_resolver: Marello\Bundle\DataGridBundle\Grid\FormatterContextResolver::getResolverCurrencyClosure
                align:            right
            invoicedAt:
                frontend_type:    datetime
                label:            marello.invoice.invoiced_at.label
                renderable:       false
            createdAt:
                label:            oro.ui.created_at
                frontend_type:    datetime
            updatedAt:
                label:            oro.ui.updated_at
                frontend_type:    datetime
        sorters:
            columns:
                invoiceNumber:
                    data_name: i.invoiceNumber
                orderNumber:
                    data_name: o.orderNumber
                salesChannel:
                    data_name: i.salesChannel
                shippingMethod:
                    data_name: i.shippingMethod
                billingAddress:
                    data_name: billingName
                shippingAddress:
                    data_name: shippingName
                grandTotal:
                    data_name: i.grandTotal
                invoicedAt:
                    data_name: i.purchaseDate
                createdAt:
                    data_name: i.createdAt
                updatedAt:
                    data_name: i.updatedAt
            default:
                invoiceNumber: "%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC"
        filters:
            columns:
                invoiceNumber:
                    type: string
                    data_name: i.invoiceNumber
                orderNumber:
                    type: string
                    data_name: o.orderNumber
                salesChannel:
                    type: string
                    data_name: salesChannelName
                shippingMethod:
                    type: string
                    data_name: i.shippingMethod
                billingAddress:
                    type: string
                    data_name: billingName # This alias is generated using InvoiceGridAddressFilterListener
                shippingAddress:
                    type: string
                    data_name: shippingName # This alias is generated using InvoiceGridAddressFilterListener
                createdAt:
                    type: datetime
                    data_name: i.createdAt
                updatedAt:
                    type: datetime
                    data_name: i.updatedAt
        options:
            export: true
            mass_actions:
                delete:
                    enabled: false

    marello-invoices-grid:
        extends: marello-invoices-base-grid
        source:
            query:
                where:
                    and:
                        - it.name = :invoiceType
            bind_parameters:
                -
                    name: invoiceType
                    default: invoice
                    type: string
        properties:
            view_link:
                type:   url
                route:  marello_invoice_invoice_view
                params:
                    id: id
        actions:
            view:
                type:       navigate
                link:       view_link
                icon:       eye
                rowAction:  true

    marello-order-invoices-grid:
        extends: marello-invoices-grid
        source:
            query:
                where:
                    and:
                        - o.id = :orderId
            bind_parameters:
                - orderId
        filters: ~

    marello-invoice-items:
        source:
            type: orm
            query:
                select:
                    - i
                    - inv.currency as currency
                    - product.sku as productSku
                    - product.name as productName
                from:
                    - { table: MarelloInvoiceBundle:InvoiceItem, alias: i}
                join:
                    left:
                        - { join: i.invoice, alias: inv }
                        - { join: i.product, alias: product }
                where:
                    and:
                        - i.invoice = :invoice_id
            bind_parameters:
                invoice_id: invoiceId
        columns:
            productSKU:
                label:            marello.product.sku.label
                frontend_type:    string
                data_name:        productSku
            productName:
                label:            marello.product.name.label
                frontend_type:    string
                data_name:        productName
            quantity:
                label:            marello.invoice.invoiceitem.quantity.label
                frontend_type:    number
            price:
                label:            marello.invoice.invoiceitem.price.label
                type:             localized_number
                method:           formatCurrency
                context_resolver: Marello\Bundle\DataGridBundle\Grid\FormatterContextResolver::getRootResolverCurrencyClosure
                align:            right
            tax:
                label:            marello.invoice.invoiceitem.tax.label
                type:             localized_number
                method:           formatCurrency
                context_resolver: Marello\Bundle\DataGridBundle\Grid\FormatterContextResolver::getRootResolverCurrencyClosure
                align:            right
            rowTotalInclTax:
                label:            marello.invoice.invoiceitem.row_total_incl_tax.label
                type:             localized_number
                method:           formatCurrency
                context_resolver: Marello\Bundle\DataGridBundle\Grid\FormatterContextResolver::getRootResolverCurrencyClosure
                align:            right
            rowTotalExclTax:
                label:            marello.invoice.invoiceitem.row_total_excl_tax.label
                type:             localized_number
                method:           formatCurrency
                context_resolver: Marello\Bundle\DataGridBundle\Grid\FormatterContextResolver::getRootResolverCurrencyClosure
                align:            right

    marello-creditmemos-grid:
        extends: marello-invoices-base-grid
        source:
            query:
                where:
                    and:
                        - it.name = :invoiceType
            bind_parameters:
                -
                    name: invoiceType
                    default: creditmemo
                    type: string
        properties:
            view_link:
                type:   url
                route:  marello_invoice_creditmemo_view
                params:
                    id: id
        actions:
            view:
                type:       navigate
                link:       view_link
                icon:       eye
                rowAction:  true