services:
    marello_refund.workflow.create_refund_action:
        class: Marello\Bundle\RefundBundle\Workflow\Actions\CreateRefundAction
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@doctrine'
        tags:
            - { name: oro_action.action, alias: marello_create_refund }

    marello_refund.twig.refund_extension:
        class: Marello\Bundle\RefundBundle\Twig\RefundExtension
        arguments:
            - '@oro_workflow.manager'
        tags:
            - { name: twig.extension }

    marello_refund.datagrid.action_permission_provider:
        class: Marello\Bundle\RefundBundle\Datagrid\RefundActionPermissionProvider
        arguments:
            - '@doctrine.orm.entity_manager'