api:
    entity_aliases:
        MarelloEnterprise\Bundle\InstoreAssistantBundle\Api\Model\InstoreUserApi:
            alias: instoreuser
            plural_alias: instoreuser
    entities:
        MarelloEnterprise\Bundle\InstoreAssistantBundle\Api\Model\InstoreUserApi:
            documentation_resource: '@MarelloEnterpriseInstoreAssistantBundle/Resources/doc/api/instore_user_api.md'
            fields:
                id:
                    data_type:   integer
                    description: The unique identifier of a UserApi.
                apiKey:
                    data_type:    string
                    description:  Api key
            actions:
                get: false
                get_list: false
                create: false
                update: false
                delete: false
                delete_list: false
                get_subresource: false
                get_relationship: false
                update_relationship: false
                add_relationship: false
                delete_relationship: false