oro_api:
    actions:
        authenticate:
            processing_groups:
                initialize:
                    priority: -10
                resource_check:
                    priority: -15
                normalize_input:
                    priority: -20
                security_check:
                    priority: -30
                normalize_data:
                    priority: -40
                finalize:
                    priority: -50
                normalize_result:
                    priority: -60