parameters:
    marelloenterprise_inventory.form.type.warehouse_delete.handler.class: MarelloEnterprise\Bundle\InventoryBundle\Form\Handler\WarehouseDeleteHandler
services:
    marello_enterprise.form.extension.warehouse:
        class: MarelloEnterprise\Bundle\InventoryBundle\Form\Extension\WarehouseExtension
        tags:
            - { name: form.type_extension, alias: marello_warehouse }

    marello_enterprise.form.extension.inventorylevel:
        class: MarelloEnterprise\Bundle\InventoryBundle\Form\Extension\InventoryLevelExtension
        tags:
            - { name: form.type_extension, alias: marello_inventory_inventorylevel }

    marelloenterprise.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - '%marello_inventory.entity.warehouse.class%'
            - "@doctrine.orm.entity_manager"

    marelloenterprise_inventory.form.type.warehouse_delete.handler:
        class:  '%marelloenterprise_inventory.form.type.warehouse_delete.handler.class%'
        parent: oro_soap.handler.delete.abstract
        scope: request
        arguments:
            - '@marelloenterprise_inventory.validator.warehouse_delete'
            - '@oro_security.security_facade'

    # Autocomplete search handler
    marelloenterprise_inventory.form.autocomplete.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - '%marello_inventory.entity.warehouse.class%'
            - ["label"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: warehouses, acl_resource: marello_inventory_inventory_view }

    marelloenterprise_inventory.form.type.warehouse_select:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Form\Type\WarehouseSelectType'
        tags:
            - { name: form.type, alias: marello_warehouse_select }

    marelloenterprise_inventory.form.type.wfarule:
        class: 'MarelloEnterprise\Bundle\InventoryBundle\Form\Type\WFARuleType'
        arguments:
            - '@marelloenterprise_inventory.provider.wfa_strategy.choices'
            - '@marelloenterprise_inventory.repository.wfa_rule'
        tags:
            - { name: form.type, alias: marello_inventory_wfarule_type }