config:
    paths:
        'oro/select2-autocomplete-system-group-global-warehouses-component': 'bundles/marelloenterpriseinventory/js/app/components/select2-autocomplete-system-group-global-warehouses-component.js'
