parameters:
    # subscriber
    marelloenterprise_inventory.event_listener.default_warehouse_subscriber.class: MarelloEnterprise\Bundle\InventoryBundle\EventListener\Doctrine\DefaultWarehouseSubscriber

    # grid action permission provider
    marelloenterprise_inventory.datagrid.action_permission_provider.class: MarelloEnterprise\Bundle\InventoryBundle\Datagrid\WarehouseActionPermissionProvider

    #validator
    marelloenterprise_inventory.validator.default_warehouse_exists.class: MarelloEnterprise\Bundle\InventoryBundle\Validator\DefaultWarehouseExistsValidator
    marelloenterprise_inventory.validator.warehouse_delete.class: MarelloEnterprise\Bundle\InventoryBundle\Validator\WarehouseDeleteValidator

services:
    marelloenterprise_inventory.event_listener.default_warehouse_subscriber:
        class: '%marelloenterprise_inventory.event_listener.default_warehouse_subscriber.class%'
        tags:
            - { name: doctrine.event_subscriber }

    marelloenterprise_inventory.datagrid.action_permission_provider:
        class: '%marelloenterprise_inventory.datagrid.action_permission_provider.class%'

    marelloenterprise_inventory.validator.default_warehouse_exists:
        class: '%marelloenterprise_inventory.validator.default_warehouse_exists.class%'
        arguments:
            - '@doctrine'
        tags:
            - { name: validator.constraint_validator, alias: marello_enterprise_inventory.default_warehouse_exists }

    marelloenterprise_inventory.validator.warehouse_delete:
        class: '%marelloenterprise_inventory.validator.warehouse_delete.class%'