Marello\Bundle\InventoryBundle\Entity\Warehouse:
    constraints:
        - MarelloEnterprise\Bundle\InventoryBundle\Validator\Constraints\DefaultWarehouseExists: ~
Marello\Bundle\InventoryBundle\Entity\InventoryLevel:
    constraints:
        - Marello\Bundle\CoreBundle\Validator\Constraints\UniqueEntityCollection:
            fields: [warehouse, inventoryItem]
            errorPath: warehouse
            message: 'marelloenterprise.inventory.validation.messages.error.unique_warehouse_inventory_level'
    properties:
        warehouse:
            - NotBlank: ~
