services:
    marelloenterprise_replenishment.replenishment_strategy.registry:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Strategy\ReplenishmentStrategiesRegistry'

    marelloenterprise_replenishment.replenishment_strategy.equal_division:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Strategy\EqualDivision\EqualDivisionReplenishmentStrategy'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: marello_replenishment_strategy }

    marelloenterprise_replenishment.provider.replenishment_strategies_choices_provider:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Provider\ReplenishmentStrategyChoicesProvider'
        arguments:
            - '@marelloenterprise_replenishment.replenishment_strategy.registry'
            - '@translator'

    marelloenterprise_replenishment.provider.replenishment_orders_from_config:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Provider\ReplenishmentOrdersFromConfigProvider'
        arguments:
            - '@marelloenterprise_replenishment.replenishment_strategy.registry'

    marelloenterprise_replenishment.repository.replenishment_order_config:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Entity\Repository\ReplenishmentOrderConfigRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'MarelloEnterprise\Bundle\ReplenishmentBundle\Entity\ReplenishmentOrderConfig'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    marelloenterprise_replenishment.repository.replenishment_order:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Entity\Repository\ReplenishmentOrderRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'MarelloEnterprise\Bundle\ReplenishmentBundle\Entity\ReplenishmentOrder'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    marelloenterprise_replenishment.twig.replenishment_extension:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Twig\ReplenishmentExtension'
        arguments:
            - '@marelloenterprise_replenishment.replenishment_strategy.registry'
            - '@translator.default'
        tags:
            - { name: twig.extension }

    marelloenterprise_replenishment.workflow.repl_order_allocate_origin_inventory_action:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Workflow\ReplenishmentOrderAllocateOriginInventoryAction'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@event_dispatcher'
        tags:
            - { name: oro_action.action, alias: marello_allocate_origin_replenished_inventory }

    marelloenterprise_replenishment.workflow.repl_order_allocate_destination_inventory_action:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Workflow\ReplenishmentOrderAllocateDestinationInventoryAction'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@event_dispatcher'
        tags:
            - { name: oro_action.action, alias: marello_allocate_destination_replenished_inventory }

    marelloenterprise_replenishment.entity_listener.repl_order_item:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\EventListener\Doctrine\ReplenishmentOrderItemListener'
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Entity\ReplenishmentOrderItem', event: postUpdate }

    marelloenterprise_replenishment.async.create_replenishment_orders_processor:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Async\CreateReplenishmentOrdersProcessor'
        arguments:
            - '@logger'
            - '@doctrine.orm.entity_manager'
            - '@marelloenterprise_replenishment.provider.replenishment_orders_from_config'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    marelloenterprise_replenishment.command.create_delayed_replenishment_orders:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Command\CreateDelayedReplenishmentOrdersCommand'
        tags:
            - { name: console.command }