channels:
   entity_data
#       -
#          name: Marello\Bundle\MagentoBundle\Entity\Cart
#          dependent:
#              - Marello\Bundle\MagentoBundle\Entity\CartAddress
#              - Marello\Bundle\MagentoBundle\Entity\CartItem
#              - Marello\Bundle\MagentoBundle\Entity\CartStatus
#              - Marello\Bundle\MagentoBundle\Entity\Store
#              - Marello\Bundle\MagentoBundle\Entity\Website
#              - Marello\Bundle\MagentoBundle\Entity\Region
#          navigation_items:
#              - application_menu.sales_tab.magento_cart
#          belongs_to:
#              integration: magento
#              connector: cart
#
#       -
#          name: Marello\Bundle\MagentoBundle\Entity\Customer
#          dependent:
#              - Marello\Bundle\MagentoBundle\Entity\CustomerGroup
#              - Marello\Bundle\MagentoBundle\Entity\Address
#              - Marello\Bundle\MagentoBundle\Entity\Region
#              - Marello\Bundle\MagentoBundle\Entity\Website
#              - Marello\Bundle\MagentoBundle\Entity\Store
#          navigation_items:
#              - application_menu.customers_tab.magento_customer
#          belongs_to:
#              integration: magento
#              connector: customer
#
#       -
#          name: Marello\Bundle\MagentoBundle\Entity\Order
#          dependent:
#              - Marello\Bundle\MagentoBundle\Entity\OrderAddress
#              - Marello\Bundle\MagentoBundle\Entity\OrderItem
#              - Marello\Bundle\MagentoBundle\Entity\Region
#              - Marello\Bundle\MagentoBundle\Entity\Store
#              - Marello\Bundle\MagentoBundle\Entity\Website
#              - Marello\Bundle\MagentoBundle\Entity\OrderNote
#          navigation_items:
#              - application_menu.sales_tab.magento_order
#          belongs_to:
#              integration: magento
#              connector: order
#
#       -
#          name: Marello\Bundle\MagentoBundle\Entity\CreditMemo
#          dependent:
#              - Marello\Bundle\MagentoBundle\Entity\OrderAddress
#              - Marello\Bundle\MagentoBundle\Entity\CreditMemoItem
#              - Marello\Bundle\MagentoBundle\Entity\Store
#          navigation_items:
#              - application_menu.sales_tab.magento_credit_memo
#          belongs_to:
#              integration: magento
#              connector: credit_memo
#
#       -
#          name: Marello\Bundle\MagentoBundle\Entity\NewsletterSubscriber
#          dependent:
#              - Marello\Bundle\MagentoBundle\Entity\Store
#          navigation_items:
#              - application_menu.marketing_tab.magento_newsletter_subscriber
#          belongs_to:
#              integration: magento
#              connector: newsletter_subscriber
#
       -
          name: Marello\Bundle\MagentoBundle\Entity\Website

   channel_types:
        magento:
            label: oro.magento.channel_type.magento.label
#            entities:
#                - Marello\Bundle\MagentoBundle\Entity\Cart
#                - Marello\Bundle\MagentoBundle\Entity\Order
#                - Marello\Bundle\MagentoBundle\Entity\CreditMemo
#                - Marello\Bundle\MagentoBundle\Entity\NewsletterSubscriber
            integration_type: magento
#            customer_identity: Marello\Bundle\MagentoBundle\Entity\Customer
            lifetime_value: lifetime
