MarelloEnterprise\Bundle\EbayBundle\Entity\EbaySettings:
    constraints:
        - MarelloEnterprise\Bundle\EbayBundle\Validator\Constraints\ItemsLocationDoesNotMatchMarketplaceCountry: ~
        - MarelloEnterprise\Bundle\EbayBundle\Validator\Constraints\NotEnterpriseUser: ~
    properties:
        userToken:
            - NotBlank: ~
        marketplace:
            - NotBlank: ~
        currency:
            - NotBlank: ~
        shippingService:
            - NotBlank: ~
        category:
            - NotBlank: ~
