parameters:
    marello_magebridge.importexport.product_reader.class: Marello\Bundle\MageBridgeBundle\Provider\Reader\ProductReader
    marello_magebridge.importexport.product_converter.class: Marello\Bundle\MageBridgeBundle\ImportExport\Converter\ProductDataConverter
    marello_magebridge.importexport.product_export_processor.class: Marello\Bundle\MageBridgeBundle\ImportExport\Processor\ProductExportProcessor
    marello_magebridge.importexport.writer.abstract_export.class: Marello\Bundle\MageBridgeBundle\ImportExport\Writer\AbstractWriter
    marello_magebridge.importexport.product_export_writer.class: Marello\Bundle\MageBridgeBundle\ImportExport\Writer\ProductExportWriter
    marello_magebridge.importexport.serializer.product_normalizer.class: Marello\Bundle\MageBridgeBundle\ImportExport\Serializer\ProductNormalizer


services:
    #Export readers
    marello_magebridge.importexport.product_reader:
        class: '%marello_magebridge.importexport.product_reader.class%'
        public: false
        parent: 'oro_importexport.reader.entity'
        calls:
            - [setSourceEntityName, ['%oro_integration.entity.class%']]
            - [setLogger, ['@oro_integration.logger.strategy']]

    #Export converters
    marello_magebridge.importexport.product_converter:
        class: '%marello_magebridge.importexport.product_converter.class%'
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'

    #Normalizer
    marello_magebridge.importexport.serializer.product_normalizer:
        class: '%marello_magebridge.importexport.serializer.product_normalizer.class%'
        parent: oro_importexport.serializer.configurable_entity_normalizer
        calls:
            - [setEntityClass, ['%marello_product.entity.class%']]
        tags:
            - { name: oro_importexport.normalizer }


    # Export processors
    marello_magebridge.importexport.product_export_processor:
        parent: oro_integration.importexport.processor.export
        public: false
        calls:
             - [setDataConverter, ["@marello_magebridge.importexport.product_converter"]]
        tags:
            - name: oro_importexport.processor
              type: export
              entity: '%oro_integration.entity.class%'
              alias: marello_magebridge_importexport_product_processor

    # Export writers
    marello_magebridge.importexport.writer.abstract_export:
        class: '%marello_magebridge.importexport.writer.abstract_export.class%'
        parent: oro_integration.writer.persistent_batch_writer
        abstract: true
        calls:
            - [setMagentoResourceOwner, ["@hwi_oauth.resource_owner.magento"]]

    marello_magebridge.importexport.product_export_writer:
        class: '%marello_magebridge.importexport.product_export_writer.class%'
        parent: marello_magebridge.importexport.writer.abstract_export
#        calls:
#            - [setStrategy, ["@oro_magento.provider.strategy.two_way_sync.customer"]]
#            - [setStateHandler, ["@oro_magento.customer_state_handler"]]