parameters:
  marello_magebridge.transport.rest_transport.class: Marello\Bundle\MageBridgeBundle\Provider\Transport\RestTransport
  marello_magebridge.provider.magento_channel_type.class: Marello\Bundle\MageBridgeBundle\Provider\MagentoChannelType
  marello_magebridge.form.type.rest_transport_setting.class: Marello\Bundle\MageBridgeBundle\Form\Type\RestTransportSettingsFormType
  marello_magebrdige_saleschannel_multi_select.class: Marello\Bundle\MageBridgeBundle\Form\Type\SalesChannelMultiSelectType

services:
    # Providers
    marello_magebridge.provider.magento_channel_type:
        class: '%marello_magebridge.provider.magento_channel_type.class%'
        tags:
            - { name: oro_integration.channel, type: magento }

    # Integration related services
    marello_magebridge.transport.rest_transport:
        class: '%marello_magebridge.transport.rest_transport.class%'
        parent: oro_integration.transport.rest.abstract_transport
#        arguments:
#            - '@oro_importexport.serializer'
        tags:
            - { name: oro_integration.transport, type: magento_rest, channel_type: magento }

    # Forms and extensions
    marello_magebridge.form.type.rest_transport_setting:
        class: '%marello_magebridge.form.type.rest_transport_setting.class%'
#        arguments:
#            - "@oro_magento.transport.rest_transport"
#            - "@oro_magento.form.subscriber.transport_setting"
#            - "@oro_integration.manager.types_registry"
        tags:
            - { name: form.type, alias: marello_magebridge_rest_transport_setting_form_type }

    marello_magebrdige.saleschannel_multi_select:
        class: '%marello_magebrdige_saleschannel_multi_select.class%'
        arguments:
            - '@marello_sales.form.data_transformer.sales_channel'
        tags:
            - { name: form.type, alias: marello_sales_saleschannel_multi_select }

    marello_magebrdige.form.type.transport_check:
        class: Marello\Bundle\MageBridgeBundle\Form\Type\TransportAuthButtonType
        tags:
            - { name: form.type, alias: marello_magebrdige_transport_auth_button }

    marello_magebrdige.provider.transport_entity:
        class: Marello\Bundle\MageBridgeBundle\Provider\TransportEntityProvider
        arguments:
            - '@form.factory'
            - '@doctrine'

    marello_magebrdige.handler.transport:
        class: Marello\Bundle\MageBridgeBundle\Handler\TransportHandler
        scope: request
        arguments:
            - '@oro_integration.manager.types_registry'
            - '@marello_magebrdige.provider.transport_entity'
#            - '@oro_magento.provider.website_choices'
#            - '@oro_magento.provider.connector_choices'
            - '@request'


#
#integrations:
#    form:
#        synchronization_settings: # form name (now synchronization_settings and mapping_settings are available)
#            isTwoWaySyncEnabled:  # field name
#                type: checkbox    # form field type
#                options:          # form options
#                    label:    oro.integration.integration.is_two_way_sync_enabled.label
#                    required: false
#                applicable: [magento_rest]  # on which integration types this setting should be shown
