parameters:
  marello_magebridge.transport.rest_transport.class: Marello\Bundle\MageBridgeBundle\Provider\Transport\RestTransport
  marello_magebridge.provider.magento_channel_type.class: Marello\Bundle\MageBridgeBundle\Provider\MagentoChannelType
  marello_magebridge.form.type.rest_transport_setting.class: Marello\Bundle\MageBridgeBundle\Form\Type\RestTransportSettingsFormType
  marello_magebrdige.saleschannel_multi_select.class: Marello\Bundle\MageBridgeBundle\Form\Type\SalesChannelMultiSelectType

services:

    hwi_oauth.resource_owner.magento:
      class:  Marello\Bundle\MageBridgeBundle\OAuth\ResourceOwner\MagentoResourceOwner
      parent: hwi_oauth.abstract_resource_owner.oauth1

    # Providers
    marello_magebridge.provider.magento_channel_type:
        class: '%marello_magebridge.provider.magento_channel_type.class%'
        tags:
            - { name: oro_integration.channel, type: magento }

    # Integration related services
    marello_magebridge.transport.rest_transport:
        class: '%marello_magebridge.transport.rest_transport.class%'
        parent: oro_integration.transport.rest.abstract_transport
#        arguments:
#            - '@oro_importexport.serializer'
        tags:
            - { name: oro_integration.transport, type: magento_rest, channel_type: magento }

    # Forms and extensions
    marello_magebridge.form.type.rest_transport_setting:
        class: '%marello_magebridge.form.type.rest_transport_setting.class%'
#        arguments:
#            - "@oro_magento.transport.rest_transport"
#            - "@oro_magento.form.subscriber.transport_setting"
#            - "@oro_integration.manager.types_registry"
        tags:
            - { name: form.type, alias: marello_magebridge_rest_transport_setting_form_type }

    marello_magebrdige.saleschannel_multi_select:
        class: '%marello_magebrdige.saleschannel_multi_select.class%'
        arguments:
            - '@marello_sales.form.data_transformer.sales_channel'
        tags:
            - { name: form.type, alias: marello_magebridge_saleschannel_multi_select }

    marello_magebrdige.form.type.transport_check:
        class: Marello\Bundle\MageBridgeBundle\Form\Type\TransportAuthButtonType
        tags:
            - { name: form.type, alias: marello_magebrdige_transport_auth_button }

    marello_magebrdige.provider.transport_entity:
        class: Marello\Bundle\MageBridgeBundle\Provider\TransportEntityProvider
        arguments:
            - '@form.factory'
            - '@doctrine'

    marello_magebrdige.action_handler.transport_authentication:
        class: 'Marello\Bundle\MageBridgeBundle\ActionHandler\TransportTokenAuthActionHandler'
        arguments:
            - '@doctrine.orm.entity_manager'

    marello_magebrdige.handler.transport:
        class: Marello\Bundle\MageBridgeBundle\Handler\TransportHandler
        scope: request
        arguments:
            - '@oro_integration.manager.types_registry'
            - '@marello_magebrdige.provider.transport_entity'
#            - '@oro_magento.provider.website_choices'
#            - '@oro_magento.provider.connector_choices'
            - '@request'
