marello_product_product_api:
    resource:     "@MarelloProductBundle/Controller/Api/Rest/ProductController.php"
    type:         rest

oro_rest_api_product_item:
    path: /api/{entity}/{id}
    defaults:
        entity: marelloproducts
        _controller: OroApiBundle:RestApi:item
    options:
        group: rest_api
        priority: -10
