oro_menu_config:
    items:
        warehouses:
            label: marello.inventory.warehouse.entity_plural_label
            route: marelloenterprise_inventory_warehouse_index
            extras:
                routes: ['marello_inventory_warehouse_*', 'marelloenterprise_inventory_warehouse_*']
    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        warehouses: ~

oro_titles:
    marelloenterprise_inventory_warehouse_index: marello.inventory.warehouse.entity_plural_label
