operations:
    marello_magento_authenticate:
        label: marello.magebridge.magento.integration.authenticate.label
        frontend_options:
            confirmation:
                title: oro.translation.action.reset.confirm_title
                message: oro.translation.action.reset.message
                okText: oro.translation.action.reset.confirm_ok
                component: oroui/js/delete-confirmation
        applications: [default]
        acl_resource: [EDIT, $.data]
        order: 20
        datagrids:
            - oro-integration-grid
        routes:
            - oro_integration_update
        button_options:
            icon: fa-check
        attributes:
            actionAllowed:
                label: oro.integration.operation.attribute.actionAllowed.label
                type: boolean
            actionSuccess:
                label: oro.integration.operation.attribute.actionSuccess.label
                type: boolean
        preactions:
            - '@call_service_method':
                service: oro_integration.utils.edit_mode
                method: isSwitchEnableAllowed
                method_parameters: [$.data.editMode]
                attribute: $.actionAllowed
        preconditions:
            '@and':
                - '@equal': [$.actionAllowed, true]
                - '@equal': [$.data.enabled, true]
                - '@equal': [$.data.type, magento]
        actions:
            - @redirect:
                parameters:
                    route: marello_magento_integration_authenticate
                    route_parameters: {id: $.data.id}
            - '@call_service_method':
                service: marello_magebrdige.action_handler.transport_authentication
                method: handleAction
                method_parameters: [$.data.transport]
                attribute: $.actionSuccess
            - '@flash_message':
#                conditions:
#                    '@equal': [$.actionSuccess, true]
                message: marello.magebridge.magento.integration.notification.channel_linked_message
                type: 'success'
            - '@redirect': {route: "oro_integration_index"}
