operations:
    marello_magento_authenticate:
        label: marello.magebridge.magento.integration.authenticate.label
        frontend_options:
            confirmation:
                title: marello.magebrdige.action.auth.confirm_title
                message: marello.magebrdige.action.auth.message
                okText: marello.magebrdige.action.auth.confirm_ok
                component: oroui/js/standart-confirmation
        applications: [default]
        acl_resource: [EDIT, $.data]
        order: 20
        datagrids:
            - oro-integration-grid
        routes:
            - oro_integration_update
        button_options:
            icon: fa-check
        attributes:
            actionAllowed:
                label: oro.integration.operation.attribute.actionAllowed.label
                type: boolean
            actionSuccess:
                label: oro.integration.operation.attribute.actionSuccess.label
                type: boolean
        preactions:
            - '@call_service_method':
                service: oro_integration.utils.edit_mode
                method: isSwitchEnableAllowed
                method_parameters: [$.data.editMode]
                attribute: $.actionAllowed
        preconditions:
            '@and':
                - '@equal': [$.actionAllowed, true]
                - '@equal': [$.data.enabled, true]
                - '@equal': [$.data.type, magento]
        actions:
            - @redirect:
                parameters:
                    route: marello_magento_integration_authenticate
                    route_parameters: {id: $.data.id}
            - '@flash_message':
                conditions:
                    '@not_blank': [$.data.token_key]
                    '@not_blank': [$.data.token_secret]
                message: marello.magebridge.magento.integration.channel_linked_message
                type: 'success'
